#
# Cluster and Cloud Computing - Team 2 
# 
# Authors: 
#
#  * Yi Yang (Student ID: 1074365)
#  * Claire Zhang (Student ID: 1080915)
#  * Hengzhi Qiu (Student ID: 1253748)
#  * Terry (Student ID: 955797)
#  * Yonghao Hu (Student ID: 1049814)
#

# Common vars
availability_zone: melbourne-qh2-uom
instance_image: 356ff1ed-5960-4ac2-96a1-0c0198e6a999
instance_key_name: team2 # key pair name
instance_flavor: uom.mse.2c9g

# Volume
volumes:
  - vol_name: CouchDB-Master-Node-volume-data
    vol_size: 40
  - vol_name: CouchDB-Master-Node-volume-docker
    vol_size: 10
  - vol_name: CouchDB-Subnode-01-volume-data
    vol_size: 40
  - vol_name: CouchDB-Subnode-01-volume-docker
    vol_size: 10
  - vol_name: CouchDB-Subnode-02-volume-data
    vol_size: 40
  - vol_name: CouchDB-Subnode-02-volume-docker
    vol_size: 10
  - vol_name: Main-Server-volume-data
    vol_size: 40
  - vol_name: Main-Server-volume-docker
    vol_size: 10

# Security group
security_groups:
  - name: administration
    description: "Security group for server administration and remote access (e.g. access via SSH or HTTP for Frontend)"
  - name: intra_cluster_communication
    description: "Security group for communication between CouchDB nodes in cluster"

security_group_rules_public: 
  - name: administration
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: administration
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_ip_prefix: 0.0.0.0/0
  - name: administration
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0
  - name: administration
    protocol: tcp
    port_range_min: 8000
    port_range_max: 8000
    remote_ip_prefix: 0.0.0.0/0

security_group_rules_private: 
  - name: intra_cluster_communication
    protocol: tcp
    port_range_min: 9100
    port_range_max: 9200
    remote_group: intra_cluster_communication
  - name: intra_cluster_communication
    protocol: tcp
    port_range_min: 5984
    port_range_max: 5984
    remote_group: intra_cluster_communication
  - name: intra_cluster_communication
    protocol: tcp
    port_range_min: 4369
    port_range_max: 4369
    remote_group: intra_cluster_communication


# Instance
instances:
  - name: CouchDB-Master-Node
    volumes: ['CouchDB-Master-Node-volume-data', 'CouchDB-Master-Node-volume-docker']
  - name: CouchDB-Subnode-01
    volumes: ['CouchDB-Subnode-01-volume-data', 'CouchDB-Subnode-01-volume-docker']
  - name: CouchDB-Subnode-02
    volumes: ['CouchDB-Subnode-02-volume-data', 'CouchDB-Subnode-02-volume-docker']
  - name: Main-Server
    volumes: ['Main-Server-volume-data', 'Main-Server-volume-docker']

