#
# Cluster and Cloud Computing - Team 2 
# 
# Authors: 
#
#  * Yi Yang (Student ID: 1074365)
#  * Claire Zhang (Student ID: 1080915)
#  * Hengzhi Qiu (Student ID: 1253748)
#  * Terry (Student ID: 955797)
#  * Yonghao Hu (Student ID: 1049814)
#

# Set up instances and volumes on MRC
# - hosts: localhost
#   vars_files:
#     - host_vars/MRC.yaml
#   gather_facts: true

#   roles:
#     - role: openstack-volume
#     - role: openstack-security-group
#     - role: openstack-instance

# # Install Docker and CouchDB for Data Nodes
# - hosts: DataNodes
#   vars_files:
#     - host_vars/couchdb.yaml
#   gather_facts: true
#   vars:
#     - ansible_python_interpreter: /usr/bin/python3
#     - ansible_user: ubuntu
#     - ansible_ssh_private_key_file: ~/.ssh/team2.pem
#     - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
#   roles:
#     - role: common-setup
#     - role: docker-setup
#     - role: volume-mount
#     - role: couchdb-setup

# Install Docker and CouchDB for Process Node
# - hosts: ProcessNode
#   vars_files:
#     - host_vars/couchdb.yaml
#   gather_facts: true
#   vars:
#     - ansible_python_interpreter: /usr/bin/python3
#     - ansible_user: ubuntu
#     - ansible_ssh_private_key_file: ~/.ssh/team2.pem
#     - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
#   roles:
#     - role: common-setup
#     - role: docker-setup
#     - role: volume-mount
#     - role: couchdb-setup

#  # Perform CouchDB configuration on all hosts except Masternode
# - hosts: DataNodes:!Masternode
#   vars_files:
#     - host_vars/couchdb.yaml
#   gather_facts: true
#   vars:
#     - ansible_python_interpreter: /usr/bin/python3
#     - ansible_user: ubuntu
#     - ansible_ssh_private_key_file: ~/.ssh/team2.pem
#     - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

#   roles:
#     - role: couchdb-cluster-setup

# # Install Twitter Harvester and Data analyzer
# - hosts: Masternode
#   vars_files:
#     - host_vars/application_env.yaml
#   gather_facts: true
#   vars:
#     - ansible_python_interpreter: /usr/bin/python3
#     - ansible_user: ubuntu
#     - ansible_ssh_private_key_file: ~/.ssh/team2.pem
#     - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

#   roles:
#      - role: project-clone
#      - role: twitter-harvester-setup
#      - role: data-analytics-setup


# Install data analytics scripts and React frontend
- hosts: ProcessNode
  vars_files:
    - host_vars/application_env.yaml
  gather_facts: true
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_user: ubuntu
    - ansible_ssh_private_key_file: ~/.ssh/team2.pem
    - ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  roles:
    - role: project-clone
    - role: web-setup