#
# Cluster and Cloud Computing - Team 2 
# 
# Authors: 
#
#  * Yi Yang (Student ID: 1074365)
#  * Claire Zhang (Student ID: 1080915)
#  * Hengzhi Qiu (Student ID: 1253748)
#  * Terry (Student ID: 955797)
#  * Yonghao Hu (Student ID: 1049814)
#
---
- name: Install dependencies
  tags: 'volumes'
  become: yes
  apt:
    name: ['xfsprogs']
    state: latest
    install_recommends: no
    update_cache: yes
  environment: "{{ proxy_env }}"

- name: Make file system
  tags: 'volumes'
  become: yes
  filesystem:
    fstype: xfs
    dev: "{{ item.device }}"
  when: item.device is defined
  with_items:
    - "{{ volumes }}"

- name: Checking folders
  tags: 'volumes'
  become: yes
  stat:
    path: "{{ item.mountpoint }}"
  register: directory_stats
  with_items:
    - "{{ volumes }}"

- name: Create directory
  tags: 'volumes'
  become: yes
  file:
    path: "{{ item.item.mountpoint }}"
    recurse: yes
    state: directory
  when: item.stat.exists == false
  with_items:
    - "{{ directory_stats.results }}"

- name: Mount device
  tags: 'volumes'
  become: yes
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.device }}"
    fstype: xfs
    state: mounted
  when: item.device is defined
  with_items:
    - "{{ volumes }}"